In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('Dataset of Diabetes .csv')
df.head()

ID  No_Pation Gender  AGE  Urea  Cr  HbA1c  Chol   TG  HDL  LDL  VLDL  \
0  502      17975      F   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5   
1  735      34221      M   26   4.5  62    4.9   3.7  1.4  1.1  2.1   0.6   
2  420      47975      F   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5   
3  680      87656      F   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5   
4  504      34223      M   33   7.1  46    4.9   4.9  1.0  0.8  2.0   0.4   

    BMI CLASS  
0  24.0     N  
1  23.0     N  
2  24.0     N  
3  24.0     N  
4  21.0     N

In [3]:
df.tail()

ID  No_Pation Gender  AGE  Urea  Cr  HbA1c  Chol   TG  HDL  LDL  VLDL  \
995  200     454317      M   71  11.0  97    7.0   7.5  1.7  1.2  1.8   0.6   
996  671     876534      M   31   3.0  60   12.3   4.1  2.2  0.7  2.4  15.4   
997  669      87654      M   30   7.1  81    6.7   4.1  1.1  1.2  2.4   8.1   
998   99      24004      M   38   5.8  59    6.7   5.3  2.0  1.6  2.9  14.0   
999  248      24054      M   54   5.0  67    6.9   3.8  1.7  1.1  3.0   0.7   

      BMI CLASS  
995  30.0     Y  
996  37.2    Y   
997  27.4    Y   
998  40.5    Y   
999  33.0    Y

In [4]:
df.columns

Index(['ID', 'No_Pation', 'Gender', 'AGE', 'Urea', 'Cr', 'HbA1c', 'Chol', 'TG',
       'HDL', 'LDL', 'VLDL', 'BMI', 'CLASS'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   ID         1000 non-null   int64  
 1   No_Pation  1000 non-null   int64  
 2   Gender     1000 non-null   object 
 3   AGE        1000 non-null   int64  
 4   Urea       1000 non-null   float64
 5   Cr         1000 non-null   int64  
 6   HbA1c      1000 non-null   float64
 7   Chol       1000 non-null   float64
 8   TG         1000 non-null   float64
 9   HDL        1000 non-null   float64
 10  LDL        1000 non-null   float64
 11  VLDL       1000 non-null   float64
 12  BMI        1000 non-null   float64
 13  CLASS      1000 non-null   object 
dtypes: float64(8), int64(4), object(2)
memory usage: 109.5+ KB


In [6]:
df.describe()

ID     No_Pation          AGE         Urea           Cr  \
count  1000.000000  1.000000e+03  1000.000000  1000.000000  1000.000000   
mean    340.500000  2.705514e+05    53.528000     5.124743    68.943000   
std     240.397673  3.380758e+06     8.799241     2.935165    59.984747   
min       1.000000  1.230000e+02    20.000000     0.500000     6.000000   
25%     125.750000  2.406375e+04    51.000000     3.700000    48.000000   
50%     300.500000  3.439550e+04    55.000000     4.600000    60.000000   
75%     550.250000  4.538425e+04    59.000000     5.700000    73.000000   
max     800.000000  7.543566e+07    79.000000    38.900000   800.000000   

             HbA1c         Chol           TG          HDL          LDL  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean      8.281160     4.862820     2.349610     1.204750     2.609790   
std       2.534003     1.301738     1.401176     0.660414     1.115102   
min       0.900000     0.000000     0.300000     0.200000     0.300000   
25%       6.500000     4.000000     1.500000     0.900000     1.800000   
50%       8.000000     4.800000     2.000000     1.100000     2.500000   
75%      10.200000     5.600000     2.900000     1.300000     3.300000   
max      16.000000    10.300000    13.800000     9.900000     9.900000   

              VLDL          BMI  
count  1000.000000  1000.000000  
mean      1.854700    29.578020  
std       3.663599     4.962388  
min       0.100000    19.000000  
25%       0.700000    26.000000  
50%       0.900000    30.000000  
75%       1.500000    33.000000  
max      35.000000    47.750000

In [7]:
df['CLASS'].unique()

array(['N', 'N ', 'P', 'Y', 'Y '], dtype=object)

In [8]:
df['CLASS'] = df['CLASS'].replace({'N ': 'N', 'Y ': 'Y'})

In [9]:
df['CLASS'].unique()

array(['N', 'P', 'Y'], dtype=object)

In [10]:
df['Gender'].unique()

array(['F', 'M', 'f'], dtype=object)

In [11]:
df['Gender'] = df['Gender'].replace({'f': 'F'})

In [12]:
df['Gender'].unique()

array(['F', 'M'], dtype=object)

In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [15]:
# Drop 'ID' and 'No_Pation' columns as they are not needed for the model
data = df.drop(columns=['ID', 'No_Pation', 'Urea', 'Cr', 'HbA1c', 'Chol', 'TG', 'HDL', 'LDL', 'VLDL'])

In [16]:

# Encode categorical features
le_gender = LabelEncoder()
data['Gender'] = le_gender.fit_transform(data['Gender'])

le_class = LabelEncoder()
data['CLASS'] = le_class.fit_transform(data['CLASS'])  # Assuming CLASS is the target column

In [17]:
data.head()

Gender  AGE   BMI  CLASS
0       0   50  24.0      0
1       1   26  23.0      0
2       0   50  24.0      0
3       0   50  24.0      0
4       1   33  21.0      0

In [18]:
data.nunique()

Gender     2
AGE       50
BMI       64
CLASS      3
dtype: int64

In [19]:
# Split data into features (X) and target (y)
X = data.drop(columns=['CLASS'])
y = data['CLASS']

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [32]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score

# Initialize a Random Forest model (can use Logistic Regression, SVM, etc. too)
model = RandomForestClassifier(random_state=42)

# Train the model
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [34]:
# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')

print(f'Accuracy: {accuracy:.2f}')
print('Confusion Matrix:')
print(conf_matrix)
print(f'F1 Score: {f1:.2f}')

Accuracy: 0.86
Confusion Matrix:
[[ 11   4   6]
 [  3   1   2]
 [  8   4 161]]
F1 Score: 0.87


In [35]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score

# Initialize Logistic Regression model
log_reg_model = LogisticRegression(max_iter=1000, random_state=42)

# Train the model
log_reg_model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [37]:
# Make predictions on the test set
y_pred = log_reg_model.predict(X_test)

# Evaluate the model performance
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')

print(f'Accuracy: {accuracy:.2f}')
print('Confusion Matrix:')
print(conf_matrix)
print(f'F1 Score: {f1:.2f}')

Accuracy: 0.91
Confusion Matrix:
[[ 18   0   3]
 [  3   1   2]
 [ 10   0 163]]
F1 Score: 0.91


In [28]:
import pickle

# After training your model (log_reg_model is your trained Logistic Regression model)
with open('log_reg_model.pkl', 'wb') as f:
    pickle.dump(log_reg_model, f)

# Save the label encoder if you used one
with open('label_encoder.pkl', 'wb') as f:
    pickle.dump(le_class, f)  # Assuming le_class is your LabelEncoder instance

In [29]:
min_values = df.min()
max_values = df.max()

In [28]:
min_values

ID              1
No_Pation     123
Gender          F
AGE            20
Urea          0.5
Cr              6
HbA1c         0.9
Chol          0.0
TG            0.3
HDL           0.2
LDL           0.3
VLDL          0.1
BMI          19.0
CLASS           N
dtype: object

In [29]:
max_values

ID                800
No_Pation    75435657
Gender              M
AGE                79
Urea             38.9
Cr                800
HbA1c            16.0
Chol             10.3
TG               13.8
HDL               9.9
LDL               9.9
VLDL             35.0
BMI             47.75
CLASS               Y
dtype: object

In [39]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score

# Initialize the KNN model
# You can specify the number of neighbors (k) and other parameters
model = KNeighborsClassifier(n_neighbors=5)  # 5 is a common choice, but you can experiment with this

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Print results
print(f'Accuracy: {accuracy:.2f}')
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 0.89
Confusion Matrix:
[[ 14   2   5]
 [  4   0   2]
 [  8   2 163]]
